### ISSUE TITLE
Identify which repos are using CI

### ISSUE THREAD

**Issue by missaugustina** [BonnyCI/ci-plunder#30]
UPDATE: moved the original issue to Issue #76

This was getting big so I broke it up into smaller pieces. This issue now only focuses on the CI identification part.

**Comment by missaugustina** [comment]
- [x] identify repos that are using TravisCI
- [x] Build a report in R notebook
- [x] Publish (and give) a slide presentation
- [x] Export the notebook to HTML

Updates:
- [x] Identify repos that are using (non TravisCI) CI

Current methods include:
- Extract hostname from Build Status tag in Readme
- Use Github API to request yaml files: appveyor, circleci, travis
- Use Github API to request Jenkins file
- Text search in events payload for: [Tt]ravis, [Jj]enkins, and "CI"

**Comment by SpamapS** [comment]
Could you scrape past PRs for statuses?

**Comment by missaugustina** [comment]
That's a good idea, I have access to their full event history via the Github Archive.

**Comment by missaugustina** [comment]
Updated issue so the scope is smaller

**Comment by missaugustina** [comment]
This was completed but never closed - https://docs.google.com/presentation/d/1rOxKnpVpNvXDJlcDZgqdNNR_DfuZKoSAEqa4YbrkwTY/edit?usp=sharing
