### ISSUE TITLE
Learn how to use SQALE

### ISSUE THREAD

**Issue by missaugustina** [BonnyCI/ci-plunder#31]
- [x] Set up the software in a VM and figure out how it works
- [x] Check out a known github repo that you have access to
- [ ] Document these results so we can make a reproducible environment

**Comment by missaugustina** [comment]
Here's the paper where Ben Cotton used it - http://funnelfiasco.com/research/cotton_thesis_with_form30.pdf

I have some notes in the Resources wikipage where I have that linked, towards the bottom: https://github.com/BonnyCI/ci-plunder/wiki/Resources

**Comment by loafyloaf** [comment]
![sonarqube_hoist](https://cloud.githubusercontent.com/assets/2438948/21908440/ba285bce-d8e1-11e6-80fd-bcce841925c7.png)

**Comment by loafyloaf** [comment]
here's what sonarqube has to say about hoist ^^^

analysis took ~9 sec

**Comment by missaugustina** [comment]
That's hilarious! Do you have a CSV or some other data output that includes the parameters that were used in the calculations? Also there should be a way to adjust the parameters weights (eg how important a particular thing is), what happens when you tweak those?

**Comment by loafyloaf** [comment]
working on that, too.  next up for laughs: nova

**Comment by loafyloaf** [comment]
![sonarqube_nova](https://cloud.githubusercontent.com/assets/2438948/21951837/1e567432-d9dc-11e6-980d-d05ff820a7b9.png)

**Comment by loafyloaf** [comment]
I have a terrible intertron connection, so nova took a good bit to download, but just slightly over 4 min to analyze.  (69 days of tech debt!!)

**Comment by missaugustina** [comment]
Found this for supporting "unofficially" supported languages in case it was necessary - https://stackoverflow.com/questions/30606175/importing-go-source-and-coverage-into-sonarqube
