### ISSUE TITLE
Try to compare a repository with a previous version of itself

### ISSUE THREAD

**Issue by missaugustina** [BonnyCI/ci-plunder#44]
Can we run the SQALE tool against different points in time for a project? A good control test would be to run it against the very first commit (eg, README creation if the project was originally created on Github) and see if the tool lets us do that.

**Comment by loafyloaf** [comment]
yes!  sonarqube keeps the results of past scans.  the ui shows how the current scan compares to the immediately preceding scan (see attached screenshot); we can surely use its underlying database to compare results for any time period desired...
![sonarqube_hoist_comparison](https://cloud.githubusercontent.com/assets/2438948/22119779/e05208ea-de4a-11e6-9745-4e2e2bd54d32.png)

**Comment by missaugustina** [comment]
This is awesome! I'm going to close this out as complete since we now know it can.
